"""Initial

Revision ID: 342b8f7386db
Revises: 
Create Date: 2024-04-12 22:10:09.192329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342b8f7386db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptance',
    sa.Column('acceptance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('acceptance_id')
    )
    op.create_table('discount',
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', name='discountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('discount_id')
    )
    op.create_table('posting',
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('posting_status', sa.Enum('IN_ITEM_PICK', 'SENT', 'CANCELED', name='postingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('not_found', sa.UUID(), nullable=True),
    sa.Column('task_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_table('sku',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('actual_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('accepted_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('stock', sa.Enum('VALID', 'DEFECT', 'NOT_FOUND', name='skuitemstock'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('acceptance_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_id'], ['acceptance.acceptance_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_sku_association',
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.discount_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.PrimaryKeyConstraint('discount_id', 'sku_id')
    )
    op.create_table('item',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('stock', sa.Enum('VALID', 'DEFECT', 'NOT_FOUND', name='skuitemstock'), nullable=False),
    sa.Column('reserved_state', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('ordered_goods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.posting_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('acceptance_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('PICKING', 'PLACING', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_WORK', 'CANCELED', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('task_target_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_id'], ['acceptance.acceptance_id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.posting_id'], ),
    sa.ForeignKeyConstraint(['task_target_id'], ['item.item_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('ordered_goods')
    op.drop_table('item')
    op.drop_table('discount_sku_association')
    op.drop_table('accepted_items')
    op.drop_table('sku')
    op.drop_table('posting')
    op.drop_table('discount')
    op.drop_table('acceptance')
    # ### end Alembic commands ###
