"""currect some

Revision ID: 5d62b5ed1ab8
Revises: 342b8f7386db
Create Date: 2024-04-13 19:43:58.856188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d62b5ed1ab8'
down_revision: Union[str, None] = '342b8f7386db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'task_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('task_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
